[package]
name = "form-client"
version = "0.1.0"
authors = ["huntermatuse"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.7", features = ["router"] }
futures-util = "0.3.32"
gloo-timers = { version = "0.4.0", features = ["futures"] }
reqwest = { version = "0.13.3", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
js-sys = "0.3.97"
web-sys = { version = "0.3.97", features = ["Window", "Storage"] }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
server = ["dioxus/server"]

[build-dependencies]
chrono = "0.4.44"
