[application]
[web]
app_title = "Forms"
index_html = "index.html"
[web.app]

# HTML title tag content
title = "Form Client"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
